name: SonarCloud
on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup environment
        run: |
          bundle install
      - name: Build
        shell: bash
        run: |
          curl -L -O https://sonarcloud.io/static/cpp/build-wrapper-macosx-x86.zip
          unzip -o build-wrapper-macosx-x86.zip
          /Users/runner/work/paystack-ios/paystack-ios/build-wrapper-macosx-x86/build-wrapper-macosx-x86 --out-dir DerivedData\compilation-database \
          xcodebuild \
                -scheme "PaystackiOS Tests"\
                -derivedDataPath DerivedData\
                -enableCodeCoverage "YES"\
                -destination 'platform=iOS Simulator,name=iPhone 8,OS=14.4'\
                test

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: SonarCloud Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          gem install slather  
          brew install sonar-scanner
          bundle exec fastlane metrics
